print() 
name = input('What is your name? ')
print() 
color = input('What is your favorite color? ')
print(name + ', what are the odds? My favorite color is also ' + '"' + color + '"!')
print() 
notcc = input('Now that we are friends ' + name +', what is your credit card number? ')
print() 
print('"' + notcc + '"' + ', really? It was worth a try ' + name + '. Looks like you caught me "' + color + '" handed!')
print()
input(name + '! What was that - over there? ')
print('\n\n\n\n\n\n\n\n')
print('... made you click, classic misdirection tactic. Catch me if you can!')
print('\n\n\n\n')